# Generated by Django 5.2.3 on 2025-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisresult_explanation_analysisresult_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='language',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
